# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.1.1.dev14+ge60716a.d20230816'
__version_tuple__ = version_tuple = (1, 1, 1, 'dev14', 'ge60716a.d20230816')
